---
title: "Untitled"
output: html_document
---

```{r}
library(data.table)
setwd("~/Documents/datafest/")
```


```{r}
#Reading the files in
games <- fread("games.csv")
#gps <- fread("gps.csv")
rpe <- fread("rpe.csv")
wellness <- fread("wellness.csv")
```


```{r}
#Summary Stats
library(dplyr)
rpe %>% group_by (Training) %>% summarise(mean = mean(RPE))
rpe %>% filter(Training == "No") %>% summarise (n = n())
```


```{r}
#Subsetting required variables
subset <- wellness[,c(1:6, 9:15, 18:19)]
```


```{r}
#Cleaning out missing values
library(stringr)
colSums(is.na(subset))
subset$Menstruation[is.na(subset$Menstruation)] <- "No"
subset$Nutrition[is.na(subset$Nutrition)] <- "Okay"
subset$Menstruation[is.na(subset$Menstruation)] <- "No"
subset$USG[is.na(subset$USG)] <- mean(subset$USG, na.rm = TRUE)
subset$TrainingReadiness <- str_remove_all(subset$TrainingReadiness, "%")
subset$TrainingReadiness <- as.numeric(subset$TrainingReadiness)
```


```{r}
#Standardizing subjective scores
subset <- group_by(subset, PlayerID) %>% mutate (StandardizedFatigue = as.numeric(scale(Fatigue)))
subset <- group_by(subset, PlayerID) %>% mutate (StandardizedSoreness = as.numeric(scale(Soreness)))
subset <- group_by(subset, PlayerID) %>% mutate (StandardizedDesire = as.numeric(scale(Desire)))
subset <- group_by(subset, PlayerID) %>% mutate (StandardizedIrritability = as.numeric(scale(Irritability)))
subset <- group_by(subset, PlayerID) %>% mutate (StandardizedSQual = as.numeric(scale(SleepQuality)))
subset <- group_by(subset, PlayerID) %>% mutate (StandardizedMonitoringScore = as.numeric(scale(MonitoringScore)))
subset <- group_by(subset, PlayerID) %>% mutate (StandardizedTReadiness = as.numeric(scale(TrainingReadiness)))
```


```{r}
#Further subsetting to remove unimportant variables
subset_2 <- subset[,-1:-3]
```


```{r}
#Converting catefegorical to factors 
cols <- colnames(subset_2)[7:10]
subset_2[cols] <- lapply(subset_2[cols], factor)
```


```{r}
#Cleaning and categorising dates of the tournament
library(lubridate)
subset$month <- months(as.Date(subset$Date))
subset$MonthOfSeason <- ifelse(subset$month == "August", 1,
                     ifelse(subset$month == "September", 2,
                     ifelse(subset$month == "October", 3, 
                     ifelse(subset$month == "November", 4,
                     ifelse(subset$month == "December", 5, 
                     ifelse(subset$month == "January", 6,
                     ifelse(subset$month == "February", 7,
                     ifelse(subset$month == "March", 8,
                     ifelse(subset$month == "April", 9, 
                     ifelse(subset$month == "May", 10, 
                     ifelse(subset$month == "June", 11, 12)))))))))))
```


```{r}
#Principal Component Analysis
pca_test <- subset[,c(16, 19:23)]
head(pca_test)
z <- prcomp(pca_test)
summary(z)
```


```{r}
#Creating dataframe with only components
temp_components <- z[["x"]]
```


```{r}
#Choosing optimal number of principal components
screeplot(z)
loadings <- eigen(cov(pca_test))$vectors
explvar <- loadings^2
explvar
library(factoextra)
set.seed(123)
fviz_nbclust(temp_components[,1:3], kmeans, method = "silhouette")
```


```{r}
#Elbow Method for finding the optimal number of clusters
set.seed(123)
# Compute and plot wss for k = 2 to k = 15.
k.max <- 15
#data <- scaled_data
wss <- sapply(1:k.max,function(k){kmeans(temp_components[,1:3], k, nstart=50,iter.max = 15 )$tot.withinss})
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")
```


```{r}
#K-Means Clustering
set.seed(123)
all_clusters <- kmeans(temp_components[,1:3], 5, nstart=50)
all_clusters
```


```{r}
clusters_with_data <- cbind.data.frame(subset, all_clusters$cluster)
colnames(clusters_with_data)[25] <- "Cluster"
```


```{r}
#Cluster 1
#Running a Random Forest Classifier to check for important variables
library(randomForest)
forest_data <- clusters_with_data[,c(19:22, 25)]
all1 <- filter(clusters_with_data, Cluster == 1)
forest_data$Cluster <- ifelse(forest_data$Cluster == 1, 1, 0)
forest_data$Cluster <- as.factor(forest_data$Cluster)
forest.cluster <- randomForest(Cluster ~., data=forest_data, type="classification")
varImpPlot(forest.cluster, sort = T, n.var=10 )
```


```{r}
#Cluster 2
forest_data <- clusters_with_data[,c(19:22, 25)]
all2 <- filter(clusters_with_data, Cluster == 2)
forest_data$Cluster <- ifelse(forest_data$Cluster == 2, 1, 0)
forest_data$Cluster <- as.factor(forest_data$Cluster)
forest.cluster <- randomForest(Cluster ~., data=forest_data, type="classification")
varImpPlot(forest.cluster, sort = T, n.var=10 )
```


```{r}
#Cluster 3
forest_data <- clusters_with_data[,c(19:22, 25)]
all3 <- filter(clusters_with_data, Cluster == 3)
forest_data$Cluster <- ifelse(forest_data$Cluster == 3, 1, 0)
forest_data$Cluster <- as.factor(forest_data$Cluster)
forest.cluster <- randomForest(Cluster ~., data=forest_data, type="classification")
varImpPlot(forest.cluster, sort = T, n.var=10 )
```


```{r}
#Cluster 4
forest_data <- clusters_with_data[,c(19:22, 25)]
all4 <- filter(clusters_with_data, Cluster == 4)
forest_data$Cluster <- ifelse(forest_data$Cluster == 4, 1, 0)
forest_data$Cluster <- as.factor(forest_data$Cluster)
forest.cluster <- randomForest(Cluster ~., data=forest_data, type="classification")
varImpPlot(forest.cluster, sort = T, n.var=10 )
```


```{r}
#Cluster 5
forest_data <- clusters_with_data[,c(19:22, 25)]
all5 <- filter(clusters_with_data, Cluster == 5)
forest_data$Cluster <- ifelse(forest_data$Cluster == 5, 1, 0)
forest_data$Cluster <- as.factor(forest_data$Cluster)
forest.cluster <- randomForest(Cluster ~., data=forest_data, type="classification")
varImpPlot(forest.cluster, sort = T, n.var=10 )
```


```{r}
#Looking of means of each subjective score
means_df <- clusters_with_data %>% group_by(Cluster) %>% summarise (meanStandardizedSoreness = mean(StandardizedSoreness), meanStandardizedDesire = mean(StandardizedDesire), meanStandardizedIrritability = mean(StandardizedIrritability), meanStandardizedSQual = mean(StandardizedSQual), meanStandardizedMonitoringScore = mean(StandardizedMonitoringScore), meanStandardizedFatigue = mean(StandardizedFatigue))
#View(means_df)
```

```{r}
#Looking at correlations
library(corrplot)
M <- cor(clusters_with_data[,c(16, 19:23)], use = "complete.obs")
corrplot(M, method = "circle", type="upper")
```

```{r}
#Binning fatigue based on clusters found
clusters_with_data$ClusteredFatigue <- ifelse (clusters_with_data$Cluster == 1, "None",
                                       ifelse (clusters_with_data$Cluster == 4, "Mild",
                                       ifelse (clusters_with_data$Cluster == 2 | clusters_with_data$Cluster ==3, "Moderate", "Heavy")))
```


```{r}
#Viewing
table(clusters_with_data$Cluster)
table(clusters_with_data$ClusteredFatigue)
```


```{r}
wellness_game_info <- fread("finaldfv2.csv")
#View(wellness_game_info)
```


```{r}
#Spider plot for our categories of fatigue
library(fmsb)
clusters_with_data$Nutrition <- as.numeric(as.factor(clusters_with_data$Nutrition))
clusters_with_data$Pain <- as.numeric(as.factor(clusters_with_data$Pain))
clusters_with_data$Illness <- as.numeric(as.factor(clusters_with_data$Illness))
clusters_with_data$ClusteredFatigue_Factor <- as.numeric(as.factor(clusters_with_data$ClusteredFatigue))
labs = c("Absence of Soreness", "Desire", "Good Mood", "SleepQuality", "Presence of Pain")

spider.df <- clusters_with_data[,c(19,20,21,22,10,27)]

lowFatigue <- filter(spider.df, ClusteredFatigue_Factor == 4)
highFatigue <- filter(spider.df, ClusteredFatigue_Factor == 1)

colors = c("#007AC1", "#CE1141")

# get means, max, min and combine
d = data.frame(matrix(ncol=5, nrow=0))
colnames(d) <- labs
d[1,] = unname(apply(spider.df, 2, function(x) max(x, na.rm = T)))
d[2,] = unname(apply(spider.df, 2, function(x) min(x, na.rm = T)))
d[3,] = unname(apply(lowFatigue, 2, function(x) mean(x, na.rm = T)))
d[4,] = unname(apply(highFatigue, 2, function(x) mean(x, na.rm = T)))
# change last row names
rownames(d)[3:4] <- c("Low Fatigue", "High Fatigue")
radarchart(d, title = "Fatigue Defined By Clusters", pcol = colors)
legend(-2, 0, legend = c("Low Fatigue", "High Fatigue"), col=colors, lty=c(1,2))
```


```{r}
#Spider plot for given categories of fatigue
clusters_with_data$Nutrition <- as.numeric(as.factor(clusters_with_data$Nutrition))
clusters_with_data$Pain <- as.numeric(as.factor(clusters_with_data$Pain))
clusters_with_data$Illness <- as.numeric(as.factor(clusters_with_data$Illness))
clusters_with_data$ClusteredFatigue_Factor <- as.numeric(as.factor(clusters_with_data$ClusteredFatigue))

labs = c("Absence of Soreness", "Desire", "Good Mood", "SleepQuality", "Presence of Pain")

spider.df <- clusters_with_data[,c(19,20,21,22,10, 9)]

lowFatigue <- filter(spider.df, MonitoringScore > 18)
highFatigue <- filter(spider.df, MonitoringScore < 19)

colors = c("#007AC1","#CE1141")

# get means, max, min and combine
d = data.frame(matrix(ncol=5, nrow=0))
colnames(d) <- labs
#View(d)
d[1,] = unname(apply(spider.df, 2, function(x) max(x, na.rm = T)))
d[2,] = unname(apply(spider.df, 2, function(x) min(x, na.rm = T)))
d[3,] = unname(apply(lowFatigue, 2, function(x) mean(x, na.rm = T)))
d[4,] = unname(apply(highFatigue, 2, function(x) mean(x, na.rm = T)))


# change last row names
rownames(d)[3:4] <- c("Low Fatigue", "High Fatigue")

radarchart(d, title = "Fatigue Defined By Monitoring Scores", pcol = colors)
legend(-2, 0, legend = c("Low Fatigue", "High Fatigue"), col=colors, lty=c(1,2))
```

